apiVersion: v1
kind: Secret
metadata:
  name: operator-env
  labels:
{{ include "test-harness.labels" . | indent 4 }}
stringData:
  PLURAL_ACCESS_TOKEN: {{ .Values.secrets.access_token }}
  {{ if .Values.secrets.endpoint }}
  PLURAL_ENDPOINT: {{ .Values.secrets.endpoint }}
  {{ end }}