# permissions for end users to edit testsuites.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: testsuite-editor-role
rules:
- apiGroups:
  - test.plural.sh
  resources:
  - testsuites
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - test.plural.sh
  resources:
  - testsuites/status
  verbs:
  - get
