apiVersion: test.plural.sh/v1alpha1
kind: TestSuite
metadata:
  name: testsuite-sample
  namespace: plural
spec:
  repository: plural
  promoteTag: warm
  steps:
  - name: watch
    description: it wait until the app crd is ready
    template:
      container:
        image: gcr.io/pluralsh/test-base:0.1.4
        args: ["plural"]
