apiVersion: test.plural.sh/v1alpha1
kind: TestSuite
metadata:
  name: testsuite-sample
  namespace: plural
spec:
  repository: plural
  promoteTag: warm
  steps:
  - name: echo
    description: it will echo hello world
    template:
      image: busybox:latest
      command: [echo]
      args: ["hello world"]
