apiVersion: plural.sh/v1alpha1
kind: Dependencies
metadata:
  description: test-harness aws setup
  version: 0.1.0
spec:
  dependencies:
  - name: aws-bootstrap
    repo: bootstrap
    type: terraform
    version: '>= 0.1.1'
    optional: true
  providers:
  - aws
  - gcp
  - azure
  - equinix
  - kind